### ISSUE TITLE
missing requirement

### ISSUE THREAD

**Issue by LeoooooMM** [neuroninterpretation/EIIC#1]
Thank you for your wonderful work!
During running the repository code, I found some missing codes such as `dissection`, where can I obtain them?

**Comment by ncepu-eai** [comment]
Thank you for your interest in this task.



You can get the original codes of dissection from the following link:


https://github.com/CSAILVision/NetDissect

**Comment by LeoooooMM** [comment]
Thank you very much for your prompt reply! I will close this issue, thanks again

**Comment by LeoooooMM** [comment]
Sorry to ask you again:
To run the Model true and false Prediction Explanation, `data_path = 'data/per_data_results.json' definition_path = 'data/cc_definitions.json'` are needed, which are not provided in the repository, Could you please provide a demo so that I can understand the format of this data?
In addition, re-training network is mentioned in the paper, can you provide some guidance on how to retrain SVM

**Comment by neuroninterpretation** [comment]
> Sorry to ask you again: To run the Model true and false Prediction Explanation, `data_path = 'data/per_data_results.json' definition_path = 'data/cc_definitions.json'` are needed, which are not provided in the repository, Could you please provide a demo so that I can understand the format of this data? In addition, re-training network is mentioned in the paper, can you provide some guidance on how to retrain SVM

**Comment by ncepu-eai** [comment]
> Sorry to ask you again: To run the Model true and false Prediction Explanation, `data_path = 'data/per_data_results.json' definition_path = 'data/cc_definitions.json'` are needed, which are not provided in the repository, Could you please provide a demo so that I can understand the format of this data? In addition, re-training network is mentioned in the paper, can you provide some guidance on how to retrain SVM

Two demos have been added for your review. 
For retraining the SVM, we utilize the hidden states of the original models as features. For detailed information on the features selected, please refer to the paper.

Thank you.

**Comment by LeoooooMM** [comment]
Thank you very much for your prompt reply!
If possible, could you please provide the code of Re-training via CC/PE so that I can have a deeper understanding of retraining?
